# Knative Serving CRDs
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
# Install Knative Serving CRDs
# Run: kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.12.0/serving-crds.yaml
# Then: kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.12.0/serving-core.yaml

# For this setup, we'll use a script approach
